### ISSUE TITLE
Bug: `empty head` exception during training

### ISSUE THREAD

**Issue by mrupp-citrine** [CitrineInformatics/lolo#186]
When training many models via `lolopy` this error sometimes occurs (see below for a full stack trace). It only occurs for small training set sizes (n=10). It occurs non-deterministically.

This error might be related to the Poisson sampling in file `Bagger.scala`, lines 59-69.

Stack trace:
```Traceback (most recent call last):
  File "/Users/mrupp/Data/Citrine/2019-05-01_PredictiveUncertaintyBenchmark/sse-uncertainty-benchmark/smlb/smlb/results.py", line 378, in run
    result = methodf(inputs[traininds], labels[traininds], inputs[validinds])
  File "<string>", line 78, in train_and_predict
  File "/Users/mrupp/Citrine/GitHub/lolo/python/lolopy/learners.py", line 79, in fit
    result = learner.train(train_data, self.gateway.jvm.scala.Some(weights_java))
  File "/Users/mrupp/Local/anaconda3/lib/python3.7/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/Users/mrupp/Local/anaconda3/lib/python3.7/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o52491.train.
: java.lang.UnsupportedOperationException: empty.head
	at scala.collection.immutable.Vector.head(Vector.scala:185)
	at io.citrine.lolo.trees.splits.RegressionSplitter$.getBestSplit(RegressionSplitter.scala:44)
	at io.citrine.lolo.trees.regression.RegressionTreeLearner.train(RegressionTree.scala:70)
	at io.citrine.lolo.trees.regression.RegressionTreeLearner.train(RegressionTree.scala:20)
	at io.citrine.lolo.bags.Bagger.$anonfun$train$10(Bagger.scala:79)
	at io.citrine.lolo.bags.Bagger.$anonfun$train$10$adapted(Bagger.scala:74)
	at scala.collection.parallel.immutable.ParRange$ParRangeIterator.map2combiner(ParRange.scala:104)
	at scala.collection.parallel.ParIterableLike$Map.leaf(ParIterableLike.scala:1052)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Map.tryLeaf(ParIterableLike.scala:1049)
	at scala.collection.parallel.FutureTasks.$anonfun$exec$5(Tasks.scala:499)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by maxhutch** [comment]
Fixed in `develop`
